import { ArrowLeft, CalendarDays, Image as ImageIcon, MapPin, Tag } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useCallback, useEffect, useState } from 'react'
import { getIssue, normalizeIssue } from '../../api/issues'
import { AppShell } from '../../components/AppShell'
import { ErrorState, LoadingState } from '../../components/StateViews'
import { PriorityBadge, StatusBadge, TicketChip } from '../../components/UI'
import { StatusTimeline, formatDate, formatLocation } from '../../components/IssueViews'
import { useToast } from '../../context/ToastContext'

export default function IssueDetails() { const { id } = useParams(); const { push } = useToast(); const [issue, setIssue] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = useCallback(async () => { setLoading(true); setError(''); try { setIssue(normalizeIssue(await getIssue(id))) } catch (err) { setError(err.message); push(err.message, 'error') } finally { setLoading(false) } }, [id, push]); useEffect(() => { load() }, [load]); return <AppShell>{loading ? <LoadingState label="Loading issue details…" /> : error ? <ErrorState message="Unable to load this issue. Please try again." onRetry={load} /> : <><Link className="back-link" to="/app/issues"><ArrowLeft size={15} /> Back to my issues</Link><div className="detail-header"><div><TicketChip ticketId={issue.ticketId} /><h1>{issue.title}</h1><p className="detail-subtitle">Reported {formatDate(issue.createdAt)} · {issue.category}</p></div><StatusBadge status={issue.status} /></div><div className="detail-layout"><div className="detail-main"><div className="detail-card"><div className="detail-card-head"><span className="eyebrow">STATUS TIMELINE</span><PriorityBadge priority={issue.priority} /></div><StatusTimeline status={issue.status} /></div><div className="detail-card"><span className="eyebrow">THE REPORT</span><h2>{issue.title}</h2><p className="detail-description">{issue.description || 'No description was included with this report.'}</p><div className="detail-meta-grid"><div><Tag size={16} /><span><small>Category</small><strong>{issue.category}</strong></span></div><div><CalendarDays size={16} /><span><small>Reported</small><strong>{formatDate(issue.createdAt)}</strong></span></div><div><MapPin size={16} /><span><small>Location</small><strong>{formatLocation(issue)}</strong></span></div></div></div>{issue.imageUrl ? <div className="detail-card"><div className="detail-card-head"><span className="eyebrow">ATTACHED PHOTO</span><ImageIcon size={17} /></div><img className="detail-image" src={issue.imageUrl} alt={`Attached evidence for ${issue.title}`} /></div> : <div className="detail-note"><ImageIcon size={17} /><span>No photo was attached to this report.</span></div>}</div><aside className="detail-aside"><div className="aside-card"><span className="eyebrow">WHAT HAPPENS NEXT?</span><h3>Keep an eye on the timeline.</h3><p>City teams update the status as your report moves from review to resolution.</p><Link className="text-action" to="/app/issues">View all reports</Link></div><div className="aside-card aside-card-orange"><span className="eyebrow">NEED TO ADD SOMETHING?</span><p>If the situation changes, make a new report with the latest context so it can be routed correctly.</p><Link className="button button-light button-small" to="/app/report">New report</Link></div></aside></div></>}</AppShell> }
