import { Filter, ListChecks, Search, SlidersHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { listCitizenIssues, normalizeIssues } from '../../api/issues'
import { AppShell } from '../../components/AppShell'
import { PageHeader } from '../../components/DashboardBits'
import { IssueTable } from '../../components/IssueViews'
import { EmptyState, ErrorState, LoadingState } from '../../components/StateViews'
import { useToast } from '../../context/ToastContext'

export default function MyIssues() {
  const { push } = useToast(); const [issues, setIssues] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ status: '', priority: '', category: '' })
  const load = useCallback(async () => { setLoading(true); setError(''); try { setIssues(normalizeIssues(await listCitizenIssues())) } catch (err) { setError(err.message); push(err.message, 'error') } finally { setLoading(false) } }, [push]); useEffect(() => { load() }, [load])
  const filtered = useMemo(() => issues.filter((issue) => { const text = `${issue.ticketId} ${issue.title}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (!filters.status || issue.status === filters.status) && (!filters.priority || issue.priority === filters.priority) && (!filters.category || issue.category === filters.category) }), [issues, query, filters])
  const categories = [...new Set(issues.map((issue) => issue.category))]
  return <AppShell><PageHeader eyebrow="YOUR REPORTS" title="My issues" description="Search the reports you’ve made and see what’s moving." action={<Link className="button button-primary" to="/app/report">Report new issue</Link>} /><div className="filter-toolbar"><div className="search-field"><Search size={17} /><input placeholder="Search by ticket ID or title" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="filter-label"><SlidersHorizontal size={15} /> Filters</div><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option><option value="REPORTED">Reported</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select><select value={filters.priority} onChange={(e) => setFilters({ ...filters, priority: e.target.value })}><option value="">All priorities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select><select value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><option value="">All categories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></div>{loading ? <LoadingState label="Loading your reports…" /> : error ? <ErrorState message="Unable to load your issues. Please try again." onRetry={load} /> : filtered.length ? <div className="data-card"><div className="data-card-head"><div><span className="eyebrow">{filtered.length} {filtered.length === 1 ? 'REPORT' : 'REPORTS'}</span><h2>Your issue history</h2></div><span className="filter-result"><Filter size={14} /> {issues.length === filtered.length ? 'All reports' : `${filtered.length} matching`}</span></div><IssueTable issues={filtered} /></div> : <EmptyState icon={ListChecks} title={issues.length ? 'No matching issues.' : 'No issues reported yet.'} description={issues.length ? 'Try adjusting your search or filters.' : 'Your reports will live here once you make your first one.'} action={<Link className="button button-primary button-small" to="/app/report">Report your first issue</Link>} />}</AppShell>
}
