import { ArrowRight, Check, ChevronRight, CircleDot, FilePlus2, LocateFixed, ShieldCheck, Sparkles, TrendingUp, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PublicNav } from '../layout/PublicNav'
import { BrandMark } from '../components/BrandMark'

const categories = [{ icon: '⌁', label: 'Roads & potholes', count: 'Everyday access' }, { icon: '▦', label: 'Waste & cleanup', count: 'Cleaner streets' }, { icon: '◌', label: 'Streetlights', count: 'Safer nights' }, { icon: '≈', label: 'Water & drainage', count: 'Reliable services' }]
const steps = [{ number: '01', title: 'Report an issue', text: 'Share what you see with a photo, location, and a few useful details.' }, { number: '02', title: 'Authorities review it', text: 'Your report reaches the right city team with the context they need.' }, { number: '03', title: 'It gets prioritized', text: 'Teams organize reports by urgency, category, and community impact.' }, { number: '04', title: 'Track the response', text: 'See progress from the first update to a visible resolution.' }]

export default function Landing() {
  return <div className="public-page"><PublicNav /><main>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow eyebrow-pill"><span className="eyebrow-dot" /> A clearer path to city response</div><h1>Report. Track.<br /><span>Improve</span> your City.</h1><p className="hero-lead">CivicFix turns the everyday problems you notice into visible, accountable action — connecting residents with the teams who keep the city moving.</p><div className="hero-actions"><Link className="button button-primary button-large" to="/login">Report an issue <ArrowRight size={17} /></Link><Link className="text-action" to="/login">Track my issues <ChevronRight size={16} /></Link></div><div className="hero-proof"><div className="proof-avatars"><span>R</span><span>M</span><span>A</span><span>+</span></div><div><strong>Built for neighborhoods</strong><small>Every report starts with someone who cares.</small></div></div></div><div className="hero-visual"><div className="map-lines" /><div className="pulse-card"><div className="pulse-card-top"><span className="mini-label"><span className="pulse-dot" /> CITY PULSE</span><span className="live-tag">LIVE</span></div><div className="pulse-title"><strong>What’s moving in your city</strong><span>Today, 09:41</span></div><div className="pulse-metric"><span className="metric-ring"><LocateFixed size={20} /></span><div><strong>2,418</strong><span>reports in view</span></div><span className="metric-up"><TrendingUp size={14} /> 18.4%</span></div><div className="mini-chart"><span style={{ height: '36%' }} /><span style={{ height: '52%' }} /><span style={{ height: '44%' }} /><span style={{ height: '70%' }} /><span style={{ height: '58%' }} /><span className="active" style={{ height: '86%' }} /><span style={{ height: '64%' }} /><span style={{ height: '94%' }} /><span style={{ height: '76%' }} /></div><div className="issue-stream"><div><span className="stream-icon stream-orange"><FilePlus2 size={15} /></span><span><strong>Streetlight outage</strong><small>Riverstone Ave · In progress</small></span></div><span className="stream-status">active</span></div><div className="issue-stream"><div><span className="stream-icon stream-amber"><ShieldCheck size={15} /></span><span><strong>Drainage overflow</strong><small>North Quarter · Reviewing</small></span></div><span className="stream-status amber">review</span></div></div><div className="hero-pin pin-one"><CircleDot size={15} /><span>CF-0027</span></div><div className="hero-pin pin-two"><CircleDot size={15} /><span>CF-0042</span></div><div className="hero-note"><span className="note-check"><Check size={15} /></span><span><strong>Small report.</strong><br />Visible difference.</span></div></div></section>
    <section className="trust-strip"><div className="container trust-grid"><span>Designed for the people who make a city better</span><div><UsersRound size={16} /> Resident-led</div><div><ShieldCheck size={16} /> Accountable</div><div><Sparkles size={16} /> Actionable</div></div></section>
    <section className="section container" id="how-it-works"><div className="section-heading"><div><span className="eyebrow">THE CIVICFIX LOOP</span><h2>A better handoff from <span>notice</span> to response.</h2></div><p>One shared place for residents and city teams to make progress legible — without the runaround.</p></div><div className="steps-grid">{steps.map((step) => <article className="step-card" key={step.number}><span className="step-number">{step.number}</span><h3>{step.title}</h3><p>{step.text}</p><span className="step-line" /></article>)}</div></section>
    <section className="section category-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">WHAT CAN YOU REPORT?</span><h2>Local knowledge is <span>useful</span> knowledge.</h2></div><Link className="text-action" to="/login">See all issue types <ChevronRight size={16} /></Link></div><div className="category-grid">{categories.map((category) => <Link to="/login" className="category-card" key={category.label}><span className="category-symbol">{category.icon}</span><span><strong>{category.label}</strong><small>{category.count}</small></span><ArrowRight size={17} /></Link>)}</div></div></section>
    <section className="final-cta container"><div><span className="eyebrow eyebrow-light">START WHERE YOU ARE</span><h2>See a problem?<br /><span>Make it visible.</span></h2><p>Your report is more than a form. It’s the first signal in a better city response.</p></div><Link className="button button-light button-large" to="/login">Report an issue <ArrowRight size={17} /></Link><div className="cta-orbit orbit-one" /><div className="cta-orbit orbit-two" /></section>
  </main><footer className="public-footer"><div className="container footer-inner"><BrandMark light link={false} /><span>© 2026 CivicFix. Built for more responsive cities.</span><div><a href="#how-it-works">How it works</a><Link to="/login">Sign in</Link></div></div></footer></div>
}
