import { ArrowLeft, ArrowRight, Check, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { BrandMark } from '../components/BrandMark'
import { Button } from '../components/UI'
import { useAuth } from '../context/AuthContext'

export default function Signup() {
  const { register, isLoading } = useAuth(); const navigate = useNavigate()
  const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [submitted, setSubmitted] = useState(false)
  const validPassword = form.password.length >= 8
  function update(key, value) { setForm({ ...form, [key]: value }); setError('') }
  async function submit(event) { event.preventDefault(); setSubmitted(true); if (!form.name || !form.email || !validPassword) return; try { await register(form); navigate('/login', { replace: true, state: { registered: true } }) } catch (err) { setError(err.message || 'Unable to create your account. Please try again.') } }
  return <div className="auth-page auth-page-signup"><div className="auth-aside"><Link className="auth-back" to="/"><ArrowLeft size={16} /> Back to home</Link><div className="auth-aside-content"><div className="auth-mark"><span className="pulse-dot" /> CIVICFIX / RESIDENT ACCESS</div><h1>Your street<br /><span>counts.</span></h1><p>Join a clearer civic loop — report what needs attention and keep the response in view.</p><div className="signup-points"><span><Check size={14} /> Report with useful context</span><span><Check size={14} /> Follow every update</span><span><Check size={14} /> Help your neighborhood move</span></div></div><div className="auth-aside-foot"><BrandMark light link={false} /><span>Make it visible</span></div></div><div className="auth-panel"><div className="auth-panel-inner"><BrandMark /><div className="auth-form-heading"><span className="eyebrow">JOIN CIVICFIX</span><h2>Create your account</h2><p>A few details, then you’re ready to make a useful report.</p></div>{error && <div className="form-alert" role="alert">{error}</div>}<form onSubmit={submit} noValidate><label className={submitted && !form.name ? 'has-error' : ''}>Full name<div className="input-wrap"><UserRound size={17} /><input autoComplete="name" placeholder="Your name" value={form.name} onChange={(e) => update('name', e.target.value)} /></div>{submitted && !form.name && <small>Tell us your name.</small>}</label><label className={submitted && !form.email ? 'has-error' : ''}>Email address<div className="input-wrap"><Mail size={17} /><input type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={(e) => update('email', e.target.value)} /></div>{submitted && !form.email && <small>Enter a valid email address.</small>}</label><label className={submitted && !validPassword ? 'has-error' : ''}>Password<div className="input-wrap"><LockKeyhole size={17} /><input type="password" autoComplete="new-password" placeholder="At least 8 characters" value={form.password} onChange={(e) => update('password', e.target.value)} /></div><div className={`password-hint ${validPassword ? 'complete' : ''}`}><Check size={13} /> Use at least 8 characters</div>{submitted && !validPassword && <small>Choose a password with at least 8 characters.</small>}</label><Button className="button-full" loading={isLoading} type="submit">Create account <ArrowRight size={16} /></Button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></div></div>
}
