import { Check, Search, SlidersHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { listAdminIssues, normalizeIssues, updateIssue } from '../../api/issues'
import { AppShell } from '../../components/AppShell'
import { PageHeader } from '../../components/DashboardBits'
import { IssueTable } from '../../components/IssueViews'
import { ErrorState, LoadingState, EmptyState } from '../../components/StateViews'
import { Button } from '../../components/UI'
import { useToast } from '../../context/ToastContext'

export default function AdminIssues() { const { push } = useToast(); const [issues, setIssues] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ status: '', priority: '', category: '' }); const [saving, setSaving] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setIssues(normalizeIssues(await listAdminIssues())) } catch (err) { setError(err.message); push(err.message, 'error') } finally { setLoading(false) } }, [push]); useEffect(() => { load() }, [load])
  const filtered = useMemo(() => issues.filter((issue) => { const text = `${issue.ticketId} ${issue.title} ${issue.citizen?.name || issue.citizen?.email || ''}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (!filters.status || issue.status === filters.status) && (!filters.priority || issue.priority === filters.priority) && (!filters.category || issue.category === filters.category) }), [issues, query, filters]); const categories = [...new Set(issues.map((issue) => issue.category))]
  async function change(issue, field, value) { const key = `${issue.id}-${field}`; if (!issue.id) { push('This issue has no backend ID for updates.', 'error'); return } setSaving(key); try { await updateIssue(issue.id, { [field]: value }); setIssues((items) => items.map((item) => item.id === issue.id ? { ...item, [field]: value } : item)); push(`${issue.ticketId} ${field} updated.`, 'success') } catch (err) { push(err.message, 'error') } finally { setSaving('') } }
  return <AppShell variant="admin"><PageHeader eyebrow="CITY RESPONSE / ALL ISSUES" title="Manage issue flow." description="Review resident reports, adjust priority, and keep status moving with clear ownership." action={<Link className="button button-secondary" to="/admin">Back to overview</Link>} /><div className="filter-toolbar admin-filters"><div className="search-field"><Search size={17} /><input placeholder="Search ticket, title, or citizen" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="filter-label"><SlidersHorizontal size={15} /> Filter</div><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option><option>REPORTED</option><option>IN_PROGRESS</option><option>RESOLVED</option></select><select value={filters.priority} onChange={(e) => setFilters({ ...filters, priority: e.target.value })}><option value="">All priorities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select><select value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><option value="">All categories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></div>{loading ? <LoadingState label="Loading all issue records…" /> : error ? <ErrorState message="Unable to load admin issues. Please try again." onRetry={load} /> : filtered.length ? <div className="data-card"><div className="data-card-head"><div><span className="eyebrow">{filtered.length} RECORDS</span><h2>Issue operations</h2></div><span className="filter-result"><Check size={14} /> Changes save to the backend</span></div><IssueTable issues={filtered} admin onStatusChange={(issue, value) => change(issue, 'status', value)} onPriorityChange={(issue, value) => change(issue, 'priority', value)} /></div> : <EmptyState title="No issue records found." description="Try a different search or filter." />}{saving && <div className="saving-indicator">Saving change…</div>}</AppShell> }
